src/api/testAPI/get/getBookList.js
src/api/testAPI/mockData/bookList.js

book list 
test API 작성
getBookList()는 1초 후 책 리스트의 mock 데이터를 포함한 프로미스를 반환합니다.

book list test Fetch

---

src/components/App.jsx
src/components/BookList/BookList.jsx
src/components/BookList/BookList.style.js

완료 :
- 리스트형 UI생성
- 반납 버튼 기본 비활성화
- QR코드로 진입시 반납 버튼 활성화 하고 색상도 함께 변경 적용
미완성 :
- 대여버튼으로 인해 리스트 받을 시 변경 할 데이터 값 지정 필요
- 리스트는 최대 3개까지 추가할 수 있는 상위 컴포넌트(페이지) 필요

feature/#1 대여현황 리스트 컴포넌트 디자인 생성

---

src/api/testAPI/get/getBookDetail.js
src/api/testAPI/mockData/bookDetail.js

[ Mock Data 정보 ]
```
const mockBookList = [
{
title: '한 권으로 읽는 컴퓨터 구조와 프로그래밍',
author: '조너선 스타인하트',
imageUrl: 'https://search.pstatic.net/...',
},
{
title: '코딩 자율학습 HTML + CSS + 자바스크립트',
author: '김기수',
imageUrl: 'https://search.pstatic.net/....',
borrowedData: '2023.08.01',
},
{
title: '모던 자바스크립트 Deep Dive',
author: '이웅모',
imageUrl: 'https://search.pstatic.net/...',
borrowedData: '2023.08.01',
},
]
```
- 책 디테일 정보
```
export const mockBookDetail = {
title: '한 권으로 읽는 컴퓨터 구조와 프로그래밍',
author: '조너선 스타인하트',
imageUrl: 'https://search.pstatic.net/...',
bookId: 1,
borrowStatus: true,
publishYear: '2023',
bookInfo: '책 소개입니다. 이 책은 한권으로 끝내는 컴퓨터 구조와 프로그래밍의 내용을 담고 있습니다.'
}
```
- api 설명 
간단한 테스트용으로 파라미터 설정 필요 없음.
```
const getBookList = () => {
return new Promise((resolve) => {
setTimeout(() => { …
```

책 상세페이지 mock data 및 test api

---

src/components/App.jsx
src/components/BookList/BookList.jsx
src/components/BookList/BookList.style.js
src/components/Layout/Layout.style.js
src/pages/BorrowedList/Borrowedlist.style.js
src/pages/ReturnBookPage/ReturnBookPage.jsx

- 일반 대여현황 페이지(/borrowedlist) 접근시 반납 버튼은 비활성 상태.
- 반납 QR코드 페이지(/returnpage)로 접근시 반납 버튼 활성화.
- 반납 버튼 클릭 시 리스트 제거(미구현) 
- 반납 버튼 사이즈 소폭 상승
- 라우터에 반납 페이지 추가
+ 검색바 레이아웃 스타일링 수정(참고)

feature/#17 대여현황 / 반납페이지 분할 구현

---

src/components/App.jsx
src/components/Layout/Layout.jsx
src/components/LoginForm/LoginForm.style.js
src/components/ui/BackBtnWithTitle/BackBtnWithTitle.jsx
src/components/ui/BackBtnWithTitle/BackBtnWithTitle.style.js
src/pages/BorrowedList/BorrowedList.jsx

뒤로가기 및 타이틀 컴포넌트

---

src/api/Borrow/borrowAPI.js

- QR코드 도서 대출 책 상세정보 요청
fetchGETQrPage(bookNumber) 
return {BookDTO}
- 도서 대출 요청
fetchGETBorrowBook(bookNumber)
return response
- QR 도서 반납 리스트 요청 
fetchGETReturnList()
return [{BorrowDTO}, ...]
- 도서 반납 요청 
fetchGETReturnBook(bookNumber)
return response

도서 반납/대출 API 맵핑

---

src/assets/main.css
src/components/BookList/BookList.style.js
src/pages/BookListPage/BookListpage.jsx

feature/#29 

---

src/components/HowToUseModal/HowToUseModal.style.js
src/pages/Main/Main.jsx
src/pages/Main/Main.style.js

Add Main.jsx UI

---

src/assets/commonStyles/BookListContanier.style.js
src/components/AllBooks/AllBooks.jsx
src/components/App.jsx
src/components/BorrowedList/BorrowedList.jsx
src/components/ReturnList/ReturnList.jsx
src/components/SearchList/SearchList,.jsx
src/components/ui/BackBtnWithTitle/BackBtnWithTitle.jsx
src/components/ui/BackBtnWithTitle/BackBtnWithTitle.style.js
src/pages/BookListPage/BookListpage.jsx
src/pages/BorrowedListPage/BorrowedListPage.jsx
src/pages/SearchPage/SearchPage.jsx

- 도서목록페이지
- 대여현황페이지 + 반납QR
- 검색결과페이지
style: 뒤로가기 버튼 ui 스타일 수정

feat: 각page내부 로직들 컴포넌트화 작업

---

package.json
pnpm-lock.yaml
src/api/Borrow/borrowAPI.js
src/api/axiosConfig.js
src/api/user/authAPI.js
src/components/App.jsx
src/components/CreateQR/CreateQR.jsx
src/components/LoginForm/LoginForm.jsx
src/utils/validation/loginValidation.js

App.jsx의 borrowedlistPage -> borrowedlistpage로 수정

fix: borrowlistpage 대소문자 수정

---

src/components/App.jsx
src/components/BorrowedList/BorrowedList.jsx
src/components/Layout/Layout.jsx
src/components/ReturnList/ReturnList.jsx
src/components/SubMenu/SubMenu.jsx
src/constant/navigateUrl.js
src/pages/BookListPage/BookListPage.jsx
src/pages/BorrowedListPage/BorrowedListPage.jsx

경로 지정 할 거 있으면 이용해주세요!
src/constant/navigateUrl.js

경로설정 통일되도록 객체로 생성

---

src/api/Borrow/borrowAPI.js
src/api/axiosConfig.js
src/api/axiosLoginConfig.js
src/api/user/userInfo.js
src/components/CreateQR/CreateQR.jsx
src/components/Layout/Layout.jsx
src/components/LoginForm/LoginForm.jsx
src/hooks/useValidRole.js

- 유저 정보 API (인재번호, 이름, 이메일, role)
- 유저 정보 확인 hook 
- redux 유저정보 store

feat: 유저정보 관리 및 리디렉션

---

src/components/App.jsx

App.js 
import BookListPage from '../pages/BookListPage/BookListpage'; 
-> 
import BookListPage from '../pages/BookListPage/BookListPage';
파일경로 수정

fix : 파일경로 대소문자 수정

---

src/pages/BorrowBook/BorrowBook.jsx

borrowBook.jsx
import BookInfo from "../../components/Bookinfo/BookInfo";
->
import BookInfo from "../../components/Bookinfo/Bookinfo";

fix : borrowBook.jsx 파일경로 대소문자 수정

---

src/components/App.jsx
src/components/GroupTap/GroupTap.jsx
src/components/GroupTap/GroupTap.style.js
src/components/Layout/Layout.style.js
src/components/SearchList/SearchList,.jsx
src/components/SubMenu/SubMenu.jsx
src/components/SubMenu/SubMenu.style.js
src/constant/theme.js
src/pages/BookListPage/BookListPage.jsx
src/pages/SearchPage/SearchPage.jsx

feat: 그룹별 탭 추가(api연결 미구현)

---

src/components/BookStatus/BookStatus.jsx
src/components/BookStatus/BookStatus.style.js
src/components/Bookinfo/Bookinfo.jsx
src/components/Bookinfo/Bookinfo.style.js
src/components/BorrowBtn/BorrowBtn.jsx
src/components/BorrowBtn/BorrowBtn.style.js
src/components/BtnNav/BtnNav.style.js

Modify BookInfo, BorrowBtn, BookStatus UI

Modify BookInfo, BorrowBtn, BookStatus UI

---

src/api/Borrow/borrowAPI.js
src/assets/commonStyles/BookListContanier.style.js
src/components/AllBooks/AllBooks.jsx
src/components/BookList/BookList.jsx
src/components/BorrowedList/BorrowedList.jsx
src/components/ReturnList/ReturnList.jsx
src/components/SubMenu/SubMenu.jsx

+ 비동기 대기시간 동안 "로딩중입니다..." 문구 추가
+ 대여현황 / 반납 페이지에 데이터가 없을 시 "대여중인 도서가 없습니다." 추가

api 연결하여 구성(대여현황, 반납 페이지)

---

src/api/axiosConfig.js
src/api/axiosLoginConfig.js

feat: refresh 토큰 axios config 설정

---

src/api/Borrow/borrowAPI.js

책빌리기 api 수정

---

src/api/axiosConfig.js
src/components/Layout/Layout.jsx
src/components/LoginForm/LoginForm.jsx
src/components/SubMenu/SubMenu.jsx
src/hooks/useValidRole.js
src/store/userInfoSlice.js

- layout 컴포넌트 유저정보가져오는 api 호출 후 실패하면 현재 주소 저장후 /login 페이지로 리디렉션

feat: qr접근 토큰 만료 시 리디렉 설정

---

index.html
src/api/axiosConfig.js
src/api/axiosLoginConfig.js

index.html <title> 제목 변경 및 baseUrl https로 변경

index.html <title> 제목 변경 및 baseUrl https로 변경

---

src/api/axiosConfig.js
src/api/axiosLoginConfig.js

fix : api baseURL 변경

---

src/assets/commonStyles/AdminContainer.style.js
src/components/AdminLayout/AdminLayout.jsx
src/components/AdminLayout/AdminLayout.style.js
src/components/AdminMainHead/AdminMainHead.jsx
src/components/AdminMainHead/AdminMainHead.style.js
src/components/AdminSearch/AdminSearch.jsx
src/components/AdminSearch/AdminSearch.style.js
src/components/AdminTitle/AdminTitle.style.js
src/components/AsideMenu/AsideMenu.jsx
src/components/AsideMenu/AsideMenu.style.js
src/components/DateSelector/DateSelector.jsx
src/components/DateSelector/DateSelector.style.js
src/components/ExcelDownloadBtn/ExcelDownloadButton.jsx
src/components/ExcelDownloadBtn/ExcelDownloadButton.style.js
src/pages/AdminPage/AdminAddBookPage.jsx
src/pages/AdminPage/AdminBookKeeperPage.jsx
src/pages/AdminPage/AdminBookListPage.jsx
src/pages/AdminPage/AdminBorrowedListPage.jsx
src/pages/AdminPage/AdminReturnListPage.jsx
src/pages/AdminPage/AdminUserListPage.jsx

검색바 컴포넌트 스타일 후 배치
날짜선택 컴포넌트 스타일 후 배치
엑셀다운로드 버튼 스타일 후 배치
각 컴포넌트 페이지별 필요/불필요 구분하여 숨김 또는 보이게 설정함
각 컴포넌트 스타일만 완성 된 거라 동작 기능은 미구현 상태

Feature/#76 admin페이지 mainSection의 head 부분 구성

---

src/components/CreateQR/CreateQR.jsx

CreateQR 컴포넌트 내에 book number 입력 시 
QR code 이미지 센터에 book number 숫자 표시 기능 추가
다운로드 이미지에도 적용

feat: Qr code 북넘버 추가

---

index.html
src/api/Borrow/borrowAPI.js
src/api/user/adminUserAPI.js
src/components/AdminSearch/AdminSearch.jsx
src/components/AdminTbody/AdminTbody.jsx
src/components/AdminTbody/AdminTbody.style.js
src/components/Bookinfo/Bookinfo.jsx
src/components/CreateQR/CreateQR.jsx
src/pages/AdminPage/AdminUserListPage.jsx
src/pages/BookDetailPage/BookDetailPage.jsx
src/pages/BorrowBook/BorrowBook.jsx

도서지기 리스트 불러오기 API
모든 유저 리스트 불러오기 API
검색한 유저 리스트 불러오기 API
도서지기 임명 API
도서지기 해제 API
adminUserPage에서 도서지기리스트, 모든유저리스트를 불러오고 Tbody에 prop으로 넘김
Tbody에서 리스트 정보를 받아오고 state에 저장.
Tbody에서는 fetch 함수를 prop으로 받음.
만약 search param이 있으면 fetch함수를 실행시켜 검색 API호출한 후 state변경
(Tbody는 list, fetch함수 를 prop으로 받음)
Tbody에서 list를 받아와서 렌더링하고 search param이 있으면 다시 fetch 요청을보내 받아온 데이터를 다시 렌더링함.

feat: admin 도서지기 임명/해제, 유저 검색

---

src/components/AdminTbody/AdminTbody.jsx
src/components/CreateQR/CreateQR.jsx
src/pages/AdminPage/AdminUserListPage.jsx

도서지기 임명/해제 버튼 컬러 수정
admin 인재관리 페이지 중 searchbar 검색시 불필요한 리렌더링을 방지하기 위한 Tbody 컴포넌트에 isActiveSearch 프롭 추가
isActiveSearch 프롭이 false일 경우 검색 fetch가 작동하지 않음

feat: admin 인재관리 UI 수정 및 activeSearch prop 추가

---

src/api/AdminBook/AdminCheck.js
src/api/AdminBook/AdminMonthlyBorrow.js
src/api/user/adminUserAPI.js
src/components/BookListItem/BookListItem.jsx
src/components/PageNationButton/PageNationButton.jsx
src/components/PageNationButton/PageNationButton.style.js
src/pages/AdminPage/AdminUserListPage.jsx
src/pages/BookKeeperBorrowedListPage/BookKeeperBorrowedListPage.jsx
src/pages/BookKeeperMainPage/BookKeeperMainPage.jsx

feat: 도서지기 페이지

---

src/api/AdminBook/AdminMonthlyBorrow.js
src/components/BookListItem/BookListItem.jsx
src/components/BookListItem/BookListItem.style.js
src/components/StatisticsNavBox/StatisticsNavBox.jsx
src/components/StatisticsNavBox/StatisticsNavBox.style.js
src/pages/AdminPage/AdminUserListPage.jsx
src/pages/BookKeeperMainPage/BookKeeperMainPage.jsx

1. 인재관리 페이지네이션 버튼 검색 시 사라짐 
2. 도서지기 반납책 페이지 반납 버튼 크기 수정
3. 도서지기 메인 페이지 색상 및 icon 추가

feat: UI/UX 개선 예외사항 처리

---

src/api/AdminBook/AdminMonthlyBorrow.js
src/pages/BookKeeperBorrowedListPage/BookKeeperBorrowedListPage.jsx

Reverts jdncDeveloper/JDNC_Library_FE#145

Revert "feat: 무한스크롤"

---

src/api/AdminBook/AdminMonthlyBorrow.js
src/pages/BookKeeperBorrowedListPage/BookKeeperBorrowedListPage.jsx

Reverts jdncDeveloper/JDNC_Library_FE#146

Revert "Revert "feat: 무한스크롤""

---

src/components/AdminBookDetail/AddBookButton.jsx
src/components/AdminBookDetail/AdminBookDetail.jsx
src/components/AdminBookDetailInfo/AdminBookDetailInfo.jsx
src/components/AllBooks/AllBooks.jsx
src/components/App.jsx
src/components/BookSearchModal/BookSearchModal.jsx
src/components/BookSearchModal/ModalSearchList.jsx
src/components/Layout/Layout.jsx
src/components/Layout/Layout.style.js
src/constant/navigateUrl.js

Feature/#141 책 정보 검색 모달 무한스크롤 적용

---

src/components/Layout/Layout.jsx
src/components/Layout/Layout.style.js
src/components/LoginForm/LoginForm.jsx

###
1. 리디릭션시 UI노출 막기
2. login form placeholder 수정
3. login 실패시 알림

fix: 로그인 리디렉션 수정
